In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-1.4.2-cp38-cp38-macosx_10_9_x86_64.whl (11.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 3.2 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting numpy>=1.18.5
  Downloading numpy-1.22.4.zip (11.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 2.2 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.8/site-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in ./.venv/lib/python3.8/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml) ... done
  Created wheel for numpy: filename=numpy-1.22.4-cp38-cp38-macosx_10_14_x86_64.whl size=5951523 sha256=a9c01365c1968cf69eb770cd24064c5bb15e47d0469fb7f09495a7ef325c1e3f
  Stored in directory: /Users/denkitaev/Library/Caches/pip/wheels/c7/6c/43/ceeebf0411159c5857528fad0d636e0f380c017605f12c4b54
Successfully built numpy
Installing collected packages: numpy, pandas
Successfully installed numpy-1.22.4 pandas-1.4.2
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/Users/denkitaev/projects/titanic/.venv/bin/python -m pip install --upgrade pip' command.

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv('titanic.csv')

In [4]:
dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
dataset.groupby('Sex')['Survived'].count()

Sex
female    314
male      577
Name: Survived, dtype: int64

In [6]:
dataset.groupby('Sex')

In [7]:
dataset.groupby('Sex')['Survived'].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [9]:
dataset.groupby(['Sex', 'Pclass'])['Survived'].sum()

Sex     Pclass
female  1         91
        2         70
        3         72
male    1         45
        2         17
        3         47
Name: Survived, dtype: int64

In [10]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.0.6-cp38-none-macosx_10_6_universal2.whl (21.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.9/21.9 MB 3.7 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting plotly
  Downloading plotly-5.8.2-py2.py3-none-any.whl (15.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 3.9 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Requirement already satisfied: pandas>=0.24.0 in ./.venv/lib/python3.8/site-packages (from catboost) (1.4.2)
Collecting matplotlib
  Downloading matplotlib-3.5.2-cp38-cp38-macosx_10_9_x86_64.whl (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 1.6 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Requirement already satisfied: six in ./.venv/lib/python3.8/site-packages (from catboost) (1.16.0)
Collecting graphviz
  Downloading graphviz-0.20-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 KB 1.4 MB/s eta 0:00:00
Collecting scipy
  Downloading scipy-1.8.1-cp38-cp38-macosx_12_0_universal2.macosx_10_9_x86_64.whl (55.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 MB 1.8 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Requirement already satisfied: numpy>=1.16.0 in ./.venv/lib/python3.8/site-packages (from catboost) (1.22.4)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.8/site-packages (from pandas>=0.24.0->catboost) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in ./.venv/lib/python3.8/site-packages (from pandas>=0.24.0->catboost) (2.8.2)
Collecting pillow>=6.2.0
  Downloading Pillow-9.1.1-cp38-cp38-macosx_10_10_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 2.6 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.3-cp38-cp38-macosx_10_9_x86_64.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.3/65.3 KB 1.0 MB/s eta 0:00:00[31m2.1 MB/s eta 0:00:01
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.8/site-packages (from matplotlib->catboost) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in ./.venv/lib/python3.8/site-packages (from matplotlib->catboost) (3.0.9)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.33.3-py3-none-any.whl (930 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 930.9/930.9 KB 3.0 MB/s eta 0:00:00m eta 0:00:010:01:01
Collecting tenacity>=6.2.0
  Downloading tenacity-8.0.1-py3-none-any.whl (24 kB)
Installing collected packages: tenacity, scipy, pillow, kiwisolver, graphviz, fonttools, cycler, plotly, matplotlib, catboost
Successfully installed catboost-1.0.6 cycler-0.11.0 fonttools-4.33.3 graphviz-0.20 kiwisolver-1.4.3 matplotlib-3.5.2 pillow-9.1.1 plotly-5.8.2 scipy-1.8.1 tenacity-8.0.1
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/Users/denkitaev/projects/titanic/.venv/bin/python -m pip install --upgrade pip' command.

In [11]:
from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'sklearn'

In [12]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.1.1-cp38-cp38-macosx_10_13_x86_64.whl (8.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 2.8 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting joblib>=1.0.0
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.0/307.0 KB 2.9 MB/s eta 0:00:00 MB/s eta 0:00:01
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: numpy>=1.17.3 in ./.venv/lib/python3.8/site-packages (from scikit-learn) (1.22.4)
Requirement already satisfied: scipy>=1.3.2 in ./.venv/lib/python3.8/site-packages (from scikit-learn) (1.8.1)
Installing collected packages: threadpoolctl, joblib, scikit-learn
Successfully installed joblib-1.1.0 scikit-learn-1.1.1 threadpoolctl-3.1.0
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/Users/denkitaev/projects/titanic/.venv/bin/python -m pip install --upgrade pip' command.

In [13]:
from sklearn.model_selection import train_test_split

In [26]:
df = dataset.drop(["PassengerId", "Name", "Cabin", "Ticket", "Embarked"], inplace=False, axis=1)
df["IsMale"] = (df["Sex"] == "male")
del df["Sex"]
df

     Survived  Pclass   Age  SibSp  Parch     Fare  IsMale
0           0       3  22.0      1      0   7.2500    True
1           1       1  38.0      1      0  71.2833   False
2           1       3  26.0      0      0   7.9250   False
3           1       1  35.0      1      0  53.1000   False
4           0       3  35.0      0      0   8.0500    True
..        ...     ...   ...    ...    ...      ...     ...
886         0       2  27.0      0      0  13.0000    True
887         1       1  19.0      0      0  30.0000   False
888         0       3   NaN      1      2  23.4500   False
889         1       1  26.0      0      0  30.0000    True
890         0       3  32.0      0      0   7.7500    True

[891 rows x 7 columns]

In [29]:
train, test = train_test_split(df, test_size=0.2)

In [45]:
train_data = train[["Pclass", "Age", "SibSp", "Parch", "Fare", "IsMale"]]
train_labels = train["Survived"]

test_data = test[["Pclass", "Age", "SibSp", "Parch", "Fare", "IsMale"]]
test_labels = test["Survived"]

In [46]:
train_data

     Pclass   Age  SibSp  Parch     Fare  IsMale
554       3  22.0      0      0   7.7750   False
491       3  21.0      0      0   7.2500    True
694       1  60.0      0      0  26.5500    True
68        3  17.0      4      2   7.9250   False
333       3  16.0      2      0  18.0000    True
..      ...   ...    ...    ...      ...     ...
221       2  27.0      0      0  13.0000    True
675       3  18.0      0      0   7.7750    True
487       1  58.0      0      0  29.7000    True
630       1  80.0      0      0  30.0000    True
638       3  41.0      0      5  39.6875   False

[712 rows x 6 columns]

In [116]:
from catboost import CatBoostClassifier

In [117]:
model = CatBoostClassifier(iterations=50,
                           learning_rate=1,
                           depth=3)

In [118]:
model.fit(train_data, train_labels)

0:	learn: 0.4606496	total: 451us	remaining: 22.1ms
1:	learn: 0.4364842	total: 935us	remaining: 22.4ms
2:	learn: 0.4233785	total: 1.21ms	remaining: 18.9ms
3:	learn: 0.4027067	total: 1.46ms	remaining: 16.8ms
4:	learn: 0.3940227	total: 1.69ms	remaining: 15.2ms
5:	learn: 0.3902944	total: 1.92ms	remaining: 14.1ms
6:	learn: 0.3833276	total: 2.17ms	remaining: 13.4ms
7:	learn: 0.3821874	total: 2.43ms	remaining: 12.8ms
8:	learn: 0.3693727	total: 2.68ms	remaining: 12.2ms
9:	learn: 0.3631485	total: 2.9ms	remaining: 11.6ms
10:	learn: 0.3626553	total: 3.11ms	remaining: 11ms
11:	learn: 0.3621495	total: 3.32ms	remaining: 10.5ms
12:	learn: 0.3589302	total: 3.58ms	remaining: 10.2ms
13:	learn: 0.3541677	total: 3.82ms	remaining: 9.82ms
14:	learn: 0.3532211	total: 4.06ms	remaining: 9.47ms
15:	learn: 0.3523627	total: 4.31ms	remaining: 9.16ms
16:	learn: 0.3518971	total: 4.57ms	remaining: 8.88ms
17:	learn: 0.3516197	total: 4.8ms	remaining: 8.54ms
18:	learn: 0.3513773	total: 5.05ms	remaining: 8.24ms
19:	learn: 0.3460443	total: 5.32ms	remaining: 7.98ms
20:	learn: 0.3450604	total: 5.56ms	remaining: 7.67ms
21:	learn: 0.3379069	total: 5.79ms	remaining: 7.36ms
22:	learn: 0.3333330	total: 6.03ms	remaining: 7.08ms
23:	learn: 0.3312275	total: 6.27ms	remaining: 6.79ms
24:	learn: 0.3302069	total: 6.5ms	remaining: 6.5ms
25:	learn: 0.3293904	total: 6.75ms	remaining: 6.23ms
26:	learn: 0.3289794	total: 7.07ms	remaining: 6.02ms
27:	learn: 0.3287412	total: 7.45ms	remaining: 5.86ms
28:	learn: 0.3252220	total: 7.71ms	remaining: 5.58ms
29:	learn: 0.3208873	total: 7.97ms	remaining: 5.31ms
30:	learn: 0.3179398	total: 8.22ms	remaining: 5.04ms
31:	learn: 0.3175007	total: 8.48ms	remaining: 4.77ms
32:	learn: 0.3168579	total: 8.75ms	remaining: 4.51ms
33:	learn: 0.3162606	total: 9ms	remaining: 4.23ms
34:	learn: 0.3137654	total: 9.29ms	remaining: 3.98ms
35:	learn: 0.3128905	total: 9.54ms	remaining: 3.71ms
36:	learn: 0.3106609	total: 9.82ms	remaining: 3.45ms
37:	learn: 0.3077057	total: 10.1ms	remaining: 3.19ms
38:	learn: 0.3061443	total: 10.4ms	remaining: 2.92ms
39:	learn: 0.3038718	total: 10.6ms	remaining: 2.65ms
40:	learn: 0.3020630	total: 10.9ms	remaining: 2.39ms
41:	learn: 0.3001579	total: 11.1ms	remaining: 2.11ms
42:	learn: 0.3000822	total: 11.3ms	remaining: 1.84ms
43:	learn: 0.2995877	total: 11.6ms	remaining: 1.57ms
44:	learn: 0.2993405	total: 11.8ms	remaining: 1.31ms
45:	learn: 0.2985738	total: 12ms	remaining: 1.04ms
46:	learn: 0.2969216	total: 12.3ms	remaining: 782us
47:	learn: 0.2965973	total: 12.5ms	remaining: 521us
48:	learn: 0.2965109	total: 12.7ms	remaining: 259us
49:	learn: 0.2954627	total: 13ms	remaining: 0us

In [119]:
preds_class = model.predict(test_data)

In [120]:
preds_class

array([0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1])

In [121]:
for i in range(len(preds_class)):
    print(test_data.iloc[i])
    print('Label = ', test_labels.array[i], ', Prediced = ', preds_class[i], 'TRUE' if preds_class[i] == test_labels.array[i] else 'FALSE')
    print('-' * 80)

Pclass         3
Age         39.0
SibSp          0
Parch          5
Fare      29.125
IsMale     False
Name: 885, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass          1
Age          42.0
SibSp           0
Parch           0
Fare      227.525
IsMale      False
Name: 380, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass       2
Age       27.0
SibSp        0
Parch        0
Fare      26.0
IsMale    True
Name: 551, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       2
Age       23.0
SibSp        0
Parch        0
Fare      13.0
IsMale    True
Name: 733, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        1
Age        22.0
SibSp         1
Parch         0
Fare       66.6
IsMale    False
Name: 151, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass        1
Age        17.0
SibSp         1
Parch         0
Fare      108.9
IsMale    False
Name: 307, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass         3
Age          NaN
SibSp          0
Parch          0
Fare      8.4583
IsMale      True
Name: 5, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        1
Age        60.0
SibSp         1
Parch         0
Fare      75.25
IsMale    False
Name: 366, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass       2
Age       0.83
SibSp        0
Parch        2
Fare      29.0
IsMale    True
Name: 78, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass        3
Age         NaN
SibSp         1
Parch         0
Fare      24.15
IsMale     True
Name: 768, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass         3
Age         19.0
SibSp          0
Parch          0
Fare      7.8958
IsMale      True
Name: 877, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass           1
Age            NaN
SibSp            0
Parch            0
Fare      221.7792
IsMale        True
Name: 527, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       2
Age       19.0
SibSp        0
Parch        0
Fare      10.5
IsMale    True
Name: 238, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       3
Age       51.0
SibSp        0
Parch        0
Fare      7.75
IsMale    True
Name: 406, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass         1
Age         25.0
SibSp          1
Parch          2
Fare      151.55
IsMale     False
Name: 498, dtype: object
Label =  0 , Prediced =  1 FALSE
--------------------------------------------------------------------------------
Pclass         3
Age         20.0
SibSp          0
Parch          0
Fare      8.6625
IsMale      True
Name: 725, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       3
Age        4.0
SibSp        3
Parch        2
Fare      27.9
IsMale    True
Name: 63, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       3
Age        NaN
SibSp        0
Parch        0
Fare      7.05
IsMale    True
Name: 611, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass          3
Age          22.0
SibSp           0
Parch           0
Fare      10.5167
IsMale      False
Name: 882, dtype: object
Label =  0 , Prediced =  1 FALSE
--------------------------------------------------------------------------------
Pclass       2
Age       34.0
SibSp        0
Parch        0
Fare      13.0
IsMale    True
Name: 800, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        1
Age        48.0
SibSp         0
Parch         0
Fare      26.55
IsMale     True
Name: 460, dtype: object
Label =  1 , Prediced =  0 FALSE
--------------------------------------------------------------------------------
Pclass         3
Age         25.0
SibSp          0
Parch          0
Fare      7.8958
IsMale      True
Name: 794, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       3
Age       45.0
SibSp        0
Parch        0
Fare      8.05
IsMale    True
Name: 338, dtype: object
Label =  1 , Prediced =  0 FALSE
--------------------------------------------------------------------------------
Pclass         3
Age         16.0
SibSp          0
Parch          0
Fare      9.2167
IsMale      True
Name: 138, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass           1
Age           31.0
SibSp            0
Parch            2
Fare      164.8667
IsMale       False
Name: 318, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass         3
Age         17.0
SibSp          0
Parch          0
Fare      8.6625
IsMale      True
Name: 500, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       2
Age        1.0
SibSp        2
Parch        1
Fare      39.0
IsMale    True
Name: 183, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass       3
Age       43.0
SibSp        0
Parch        0
Fare      8.05
IsMale    True
Name: 668, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass         3
Age         36.0
SibSp          0
Parch          0
Fare      7.8958
IsMale      True
Name: 189, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       3
Age        NaN
SibSp        0
Parch        0
Fare      8.05
IsMale    True
Name: 589, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        3
Age        45.5
SibSp         0
Parch         0
Fare      7.225
IsMale     True
Name: 203, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass         1
Age         22.0
SibSp          0
Parch          0
Fare      151.55
IsMale     False
Name: 708, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass           1
Age           58.0
SibSp            0
Parch            1
Fare      153.4625
IsMale       False
Name: 268, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass        3
Age        22.0
SibSp         0
Parch         0
Fare       7.75
IsMale    False
Name: 289, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass          3
Age           NaN
SibSp           3
Parch           1
Fare      25.4667
IsMale      False
Name: 409, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass         3
Age         30.0
SibSp          0
Parch          0
Fare      7.8958
IsMale      True
Name: 606, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        3
Age         NaN
SibSp         0
Parch         0
Fare       8.05
IsMale    False
Name: 564, dtype: object
Label =  0 , Prediced =  1 FALSE
--------------------------------------------------------------------------------
Pclass         3
Age         28.5
SibSp          0
Parch          0
Fare      7.2292
IsMale      True
Name: 57, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       2
Age        NaN
SibSp        0
Parch        0
Fare       0.0
IsMale    True
Name: 481, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass          1
Age          23.0
SibSp           0
Parch           1
Fare      63.3583
IsMale       True
Name: 97, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass         3
Age         22.0
SibSp          0
Parch          0
Fare      7.2292
IsMale      True
Name: 60, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        3
Age         NaN
SibSp         0
Parch         0
Fare       7.75
IsMale    False
Name: 264, dtype: object
Label =  0 , Prediced =  1 FALSE
--------------------------------------------------------------------------------
Pclass          3
Age           5.0
SibSp           2
Parch           1
Fare      19.2583
IsMale      False
Name: 448, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass         3
Age          7.0
SibSp          4
Parch          1
Fare      29.125
IsMale      True
Name: 278, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        2
Age        30.0
SibSp         3
Parch         0
Fare       21.0
IsMale    False
Name: 726, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass          1
Age          42.0
SibSp           0
Parch           0
Fare      26.2875
IsMale       True
Name: 707, dtype: object
Label =  1 , Prediced =  0 FALSE
--------------------------------------------------------------------------------
Pclass          1
Age          21.0
SibSp           0
Parch           1
Fare      77.2875
IsMale       True
Name: 102, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        2
Age        18.0
SibSp         0
Parch         1
Fare       23.0
IsMale    False
Name: 651, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass        3
Age        25.0
SibSp         1
Parch         0
Fare      7.775
IsMale     True
Name: 267, dtype: object
Label =  1 , Prediced =  0 FALSE
--------------------------------------------------------------------------------
Pclass        2
Age        40.0
SibSp         0
Parch         0
Fare       13.0
IsMale    False
Name: 346, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass       3
Age        NaN
SibSp        0
Parch        0
Fare       9.5
IsMale    True
Name: 868, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        2
Age        34.0
SibSp         0
Parch         0
Fare       13.0
IsMale    False
Name: 576, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass          3
Age          12.0
SibSp           1
Parch           0
Fare      11.2417
IsMale       True
Name: 125, dtype: object
Label =  1 , Prediced =  0 FALSE
--------------------------------------------------------------------------------
Pclass       2
Age        NaN
SibSp        0
Parch        0
Fare       0.0
IsMale    True
Name: 732, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       1
Age       45.0
SibSp        0
Parch        0
Fare      35.5
IsMale    True
Name: 339, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       2
Age       29.0
SibSp        1
Parch        0
Fare      21.0
IsMale    True
Name: 117, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        3
Age        32.0
SibSp         0
Parch         0
Fare      7.925
IsMale     True
Name: 636, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       3
Age        NaN
SibSp        0
Parch        0
Fare      7.75
IsMale    True
Name: 126, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass         1
Age         35.0
SibSp          1
Parch          0
Fare      83.475
IsMale     False
Name: 230, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass         3
Age         22.0
SibSp          0
Parch          0
Fare      9.8375
IsMale     False
Name: 474, dtype: object
Label =  0 , Prediced =  1 FALSE
--------------------------------------------------------------------------------
Pclass         3
Age          NaN
SibSp          0
Parch          0
Fare      8.1375
IsMale     False
Name: 680, dtype: object
Label =  0 , Prediced =  1 FALSE
--------------------------------------------------------------------------------
Pclass         3
Age          6.0
SibSp          4
Parch          2
Fare      31.275
IsMale     False
Name: 813, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        3
Age         NaN
SibSp         0
Parch         0
Fare      7.225
IsMale     True
Name: 773, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        1
Age        35.0
SibSp         1
Parch         0
Fare       52.0
IsMale    False
Name: 383, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass       3
Age        NaN
SibSp        0
Parch        0
Fare      8.05
IsMale    True
Name: 304, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass       2
Age       28.0
SibSp        0
Parch        0
Fare      10.5
IsMale    True
Name: 883, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        2
Age        30.0
SibSp         0
Parch         0
Fare      12.35
IsMale    False
Name: 322, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass         3
Age          NaN
SibSp          0
Parch          0
Fare      7.7333
IsMale     False
Name: 697, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass          1
Age          38.0
SibSp           0
Parch           0
Fare      227.525
IsMale      False
Name: 716, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass        1
Age        52.0
SibSp         1
Parch         1
Fare       93.5
IsMale    False
Name: 820, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass          1
Age          24.0
SibSp           0
Parch           0
Fare      83.1583
IsMale      False
Name: 310, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass         3
Age         28.0
SibSp          0
Parch          0
Fare      7.8958
IsMale      True
Name: 105, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass         3
Age         39.0
SibSp          1
Parch          5
Fare      31.275
IsMale     False
Name: 610, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        3
Age         NaN
SibSp         0
Parch         0
Fare      7.225
IsMale     True
Name: 26, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        3
Age         NaN
SibSp         0
Parch         2
Fare       7.75
IsMale    False
Name: 593, dtype: object
Label =  0 , Prediced =  1 FALSE
--------------------------------------------------------------------------------
Pclass       3
Age       30.0
SibSp        0
Parch        0
Fare      8.05
IsMale    True
Name: 157, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass          2
Age          31.0
SibSp           1
Parch           1
Fare      37.0042
IsMale       True
Name: 817, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        2
Age        32.5
SibSp         0
Parch         0
Fare       13.0
IsMale    False
Name: 123, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass          3
Age          15.0
SibSp           1
Parch           0
Fare      14.4542
IsMale      False
Name: 830, dtype: object
Label =  1 , Prediced =  0 FALSE
--------------------------------------------------------------------------------
Pclass        2
Age        55.0
SibSp         0
Parch         0
Fare       16.0
IsMale    False
Name: 15, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass       2
Age       32.0
SibSp        0
Parch        0
Fare      10.5
IsMale    True
Name: 70, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass           1
Age           24.0
SibSp            0
Parch            1
Fare      247.5208
IsMale        True
Name: 118, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass          2
Age          27.0
SibSp           1
Parch           0
Fare      13.8583
IsMale      False
Name: 866, dtype: object
Label =  1 , Prediced =  1 TRUE
--------------------------------------------------------------------------------
Pclass        3
Age         NaN
SibSp         0
Parch         0
Fare      7.225
IsMale     True
Name: 354, dtype: object
Label =  0 , Prediced =  0 TRUE
--------------------------------------------------------------------------------
Pclass        1
Age        23.0
SibSp         3
Parch         2
Fare      263.0
IsMale    False

In [122]:
dataset["Fare"].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [123]:
from catboost import Pool

pool = Pool(train_data, train_labels, feature_names=list(train_data.columns))

In [124]:
model.plot_tree(
    tree_idx=1,
    pool=pool)